# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY . ./
WORKDIR /app/projeto/ProjAPI
RUN dotnet publish -c Release -o out

# Etapa de execução
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/projeto/ProjAPI/out .

ENV ASPNETCORE_URLS=http://+:10000

ENTRYPOINT ["dotnet", "ProjAPI.dll"]